/* eslint-disable react-hooks/exhaustive-deps */

import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Filter from '../components/Filter';
import ListProducts from '../components/ListProducts';
import Paginacao from '../components/Paginação';
import BodyHome from './bodyHome';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    router.push('/?page=1')
  }, []);


  return (
    <div>
      <Head>
        <title>Wine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BodyHome>
        <Filter />
        <div>
          <ListProducts />
          <Paginacao />
        </div>
      </BodyHome>
    </div>
  );
}
