import Head from 'next/head';
import Header from '../components/Header/';
import GlobalStyle from '../globalCss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <GlobalStyle />
      <Header />
    </div>
  );
}
